export const SAGA_CHECK_SESSION = 'SAGA_CHECK_SESSION';
export const SAGA_GET_REGISTRATION = 'SAGA_GET_REGISTRATION'
export const SAGA_GET_LOGIN = 'SAGA_GET_LOGIN'
export const SAGA_GET_LOGOUT = 'SAGA_GET_LOGOUT'
