export const GET_SERVICE_INFO = 'GET_SERVICE_INFO'
export const GET_SERVICE_TYPE = 'GET_SERVICE_TYPE'
export const SET_MODEL_SELECT = 'SET_MODEL_SELECT'
export const SET_MILEGE_SELECT ='SET_MILEGE_SELECT'
